### ISSUE TITLE
Issue with using "--no-handshake"

### ISSUE THREAD

**Issue by dbombara** [EmDash00/ArduinoLogger#1]
Using the option "--no-handshake" returns an issue with the ASCII encoding. Below is an example.

```
$ ./logger.py --baud=115200 --echo --no-handshake
Press enter to begin.

Traceback (most recent call last):
  File "C:\Users\dbombara\Documents\Python\ArduinoLogger\logger.py", line 335, in <module>
    main(port, baud, timeout, out, echo, handshake)
  File "C:\Users\dbombara\Documents\Python\ArduinoLogger\logger.py", line 112, in main
    msg = data[:-2].decode('ascii')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xfd in position 108: ordinal not in range(128)
```

**Comment by EmDash00** [comment]
Thanks for submitting this. We had a conversation over email about this issue; however, I think it's worth putting what might be causing it here as well. Opening the communications channel without handshaking can lead to desynchronization of communication packets. The packets are read as bytes (which are a string of 8 bits). ASCII encoding is how the Arduino represents its strings. This type of encoding supports 128 characters numbered 1-128. 0xFD is hexadecimal for for 253 in decimal. There is no such character in the ASCII encoding, so decoding the communication packet fails and raises a `UnicodeDecodeError`.

This is similar to how reading a number starting the middle can lead to a different number being read and a corruption of the message being sent. This should be able to be solved by modifying the code that decodes the line from:

```python
        data = dev.readline()
        # Arduino uses ASCII encoding
        msg = data[:-2].decode('ascii')
```

to:

```python
        data = dev.readline()
        # Arduino uses ASCII encoding

        try:
            msg = data[:-2].decode('ascii')
        except UnicodeDecodeError:
            continue
```

By catching the exception, we define to the program a set of steps to follow after encountering the UnicodeDecodeError. In this case, we ignore corrupted lines and continue accepting input. In general, though, I don't recommend using --no-handshake in applications that require consistency and should be used more for quick and dirty cases where you need some debug info and don't wish to use the Arduino Serial Monitor.
